predictor:
  type: "inapp" # can be inapp or api

anonymiser:
  max_blur_intensity: 57
  min_blur_intensity: 1

detectors:
  - class: "FaceNETDetector"
    name: "Face detection"
    description: "Can identify faces in an image. It produces bounding boxes around the targets identified in the input"
    params:
      min_face_size: 20
      thresholds:
        - 0.6
        - 0.7
        - 0.7
      device: "cuda"

  - class: "DetectronSingleDetector"
    name: "Person detection"
    description: "Can identify persons in an image. Produces both bounding boxes and segmentation masks (identifies the targets at a pixel level). The model is trained on the COCO dataset"
    params:
      cfg_name: "COCO-PanopticSegmentation/panoptic_fpn_R_50_3x.yaml"
      weights_file_name: "model_final_c10459.pkl"
      device: "cuda"
      threshold: 0.7
      target_id: 0

  - class: "OCRDetector"
    name: "Text detection"
    cfg_name: ""
    description: "Can identify English text in an image. Produces bounding boxes around the targets identified in the input"
    params:
      lang_list: # if this is updated, need to download the corresponding model
        - "en"
      gpu: True

  - class: "DetectronDetector"
    name: "Multi-class detection"
    description: "Can identify multiple common object classes in an image. Produces both bounding boxes and segmentation masks (identifies the targets at a pixel level). The model is trained on the COCO dataset"
    params:
      cfg_name: "COCO-PanopticSegmentation/panoptic_fpn_R_50_3x.yaml"
      weights_file_name: "model_final_c10459.pkl"
      device: "cuda"
      threshold: 0.7

file_io:
  flagged_path: "data_volume/flagged_images"
  feedback_path: "data_volume/feedback"
  logdir: "data_volume/logs"

visualizer:
  class: "AdaptativeVisualizer"
