anonyniser:
  url: null
  max_blur_intensity: 57
  min_blur_intensity: 1

detectors:
  - class: "FaceDetector"
    name: "Face detection and segmentation"
    description: "Can identify faces in an image. It produces bounding boxes and segmentaton masks around the targets identified in the input."
    url: null
    params:
      margin: 0
      post_process: True
      keep_all: True
      expansion: 20
      deeplab_model: "model_0044999"


  - class: "OCRDetector"
    name: "Text detection"
    cfg_name: ""
    description: "Can identify English text in an image. Produces bounding boxes around the targets identified in the input"
    url: null
    params:
      reader:
        - "ch_sim"
        - "en"
      gpu: False

  - class: "DetectronDetector"
    name: "Multi-class detection - COCO"
    description: "Can identify multiple common object classes in an image. Use this model to detect persons. Produces both bounding boxes and segmentation masks (identifies the targets at a pixel level). The model is trained on the COCO dataset"
    url: null
    params:
      cfg_name: "COCO-PanopticSegmentation/panoptic_fpn_R_50_3x.yaml"
      weights_file_name: null
      device: "cpu"
      threshold: 0.7

  - class: "DetectronDetector"
    name: "Multi-class detection - Cityscapes"
    description: "Can identify several object classes in an image. Use this model with urban street scenes. Produces both bounding boxes and segmentation masks (identifies the targets at a pixel level). The model is trained on the Cityscapes dataset"
    url: null
    params:
      cfg_name: "Cityscapes/mask_rcnn_R_50_FPN.yaml"
      weights_file_name: null
      threshold: 0.7

wandb:
  entity: fsdl_2022
  project: face-seg